### ISSUE TITLE
Price went up (will try again in 25 hours)

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#166]
I thought this would mint at 230. I'll wait until 25 hours from now and then buy another batch and mint one. I'm hoping that with the threshold now at 1 day, this will mint lower.
<img width="311" alt="image" src="https://github.com/user-attachments/assets/6468d454-9706-4419-8093-503bf11d9cd9">

**Comment by CoftheTMP** [comment]
New batch went up for the same price. I'll wait another 25 hours and try minting again, with no purchases in between
<img width="623" alt="image" src="https://github.com/user-attachments/assets/a07bd1d9-d0c7-4bf5-bad7-d5b1f58d7dc5">

**Comment by orpheuslummis** [comment]
<img width="333" alt="Screenshot 2024-10-13 at 20 01 18" src="https://github.com/user-attachments/assets/c6611636-fde8-4b22-b468-4a49fe51df2a">

I just minted a new batch. The price was 240 USD.

---

Here's the scenario we have:
- Initial price: 250 USD
- Last batch fully sold: Oct 10, 2024, 14:46:28 PM (-05:00 UTC)
- New batch minted: Oct 13, 2024, 20:00:42 PM (-05:00 UTC)
- dayDecreaseThreshold: 2 days

First calculate the time difference between the last sale and the new batch minting:
Oct 13, 20:00:42 - Oct 10, 14:46:28 = 3 days, 5 hours, 14 minutes, and 14 seconds

Now, let's apply the pricing logic:
The price doesn't start decreasing until after the dayDecrease
Threshold (2 days) has passed.
In this case, 3 days have passed, which is more than the threshold.
The price should start decreasing after 2 days.
The actual time for price decrease is: 1 day, 5 hours, 14 minutes, and 14 seconds.

However, the contract rounds down to full days when calculating the price decrease. So effectively, it's been 1 day since the price started decreasing.

The `priceDelta` (daily price decrease) is 10 USD, the calculation would be:
New Price = 250 USD - (1 day 10 USD/day) = 240 USD

Therefore, the price for this new batch minted on Oct 13, 2024, at 20:00:42 PM should be 240 USD.
